### ISSUE TITLE
arkham-horror 1.0

### ISSUE THREAD

**Issue by hone** [GeckoTH/arkham-horror#1]
I talked with @GeckoTH about the steps needed to get to a working version, 1.0. For me, this means getting OCTGN playable for Solo. This issue is going to track all that work in one place. I might them up into separate issues if it makes sense.
- [x] define groups (called piles in OCTGN) to store all the various card types in game.
  - player deck
  - player discard pile
  - act deck
  - act discard
  - agenda deck
  - agenda discard
  - location deck
  - location discard deck
  - encounter deck
  - encounter discard deck
  - a secondary encounter deck
  - a setup deck
- [x] #2 get lobby dialogue to show up
- [x] #5 define a function that when a player loads a deck, all the different card types get put into their correct piles (agenda cards go into the agenda deck, etc)
- [x]  #10 shuffle encounter discard into encounter deck
- [x] #5 Upon loading a player deck, it should also place the Investigator and mini card out on the table, and draw your starting hand, and any other basic automation we feel necessary
- [x] #9 Upon loading an encounter deck, it should place the first Agenda and Act out on the table, as well as the Scenario Card in the correct positions.
- [x] #7 Discarding a chaos token should put it back into the deck and shuffle
- [x] #8 drawing chaos tokens
- [x] #15 drawing encounter deck
- [x] #14 next Agenda
- [x] #14 next Act
- [x] #17 How do we handle giving out a random basic weakness card?
- [x] #20 next Location
- [x] #21 Don't allow drawing a weakness in opening hand
- [x] #22 double clicking on a card in your hand doesn't crash
- [ ] clean up menus to remove any LotR specific things
- [x] turn automation, on end of turn refresh cards, draw a card, give 1 resource
- [ ] double click on act should flip the card instead of adding tokens
- [ ] redo positioning of cards

## Open Questions
- Can we use "Save Deck" at the end game to continue a deck through a campaign with acquired weaknesses?
- Add horror token when you deck yourself and need to draw a card
- counter is hit for next act/agenda, highlight the card red
- lead investigator?
- check hand size on next round

**Comment by wlk0** [comment]
I think a mapped action (key or double clic) is missing to quickly tap/untap enemies.
Right now you have to right click + select rotate right since F8/F9 are already assigned to 'remove tokens'.
Double click does untap right now, but when the card is untapped it does add damages instead.

**Comment by hone** [comment]
@wlk0 thanks for the feedback! I'm aware of the F8/F9 issue. I'm going to remap it to F11/F12. As for the two handed stuff, I haven't really looked into multiplayer, but I'm not sure you can set the owner OCTGN to everyone. It has to be owned by someone. I think there are some hacks probably that can be done there. Maybe @GeckoTH can weigh in here.

**Comment by hone** [comment]
v1.0.0.0 has shipped!
